version: 2
jobs:
  build:
    working_directory: /tmp/chfse
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install npm wee
          command: npm install
     - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Generate code coverage
          command: npm run cover
          when: always

      - store_artifacts:
          path: test1/test-results.xml
          prefix: tests
      - store_artifacts:
          path: test1/coverage
          prefix: coverage
      - store_test_results:
          path: test1/test-results.xml
          prefix: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master